#!/usr/bin/env bash
# Ramp Kit setup for Cursor cloud agents, generated by `attach`.
# install: prepares .ramp-venv with the kit's pinned dependencies, then runs doctor.
# start:   reuses an existing .ramp-venv (bootstrapping only if it is missing), then runs doctor.
set -euo pipefail

PHASE=${1:?Pass install or start}
case "$PHASE" in
    install|start) ;;
    *) echo 'Expected install or start.' >&2; exit 2 ;;
esac
REPO=$(git rev-parse --show-toplevel)
cd "$REPO"

# A folder named ramp-kit (without the dot) comes from an older overlay or a
# cached environment, not from this installation. Refuse rather than build on it.
if [ -e ramp-kit ] || [ -L ramp-kit ]; then
    echo 'A legacy ramp-kit path exists in this workspace. It is not part of this installation.' >&2
    echo 'Create a fresh Cursor environment without extra repositories, custom install commands or reused snapshots; do not use this one for clean acceptance.' >&2
    exit 2
fi

if [ ! -f .ramp-kit/runtime/bootstrap.sh ]; then
    if [ "$PHASE" = install ]; then
        echo 'This branch has no Ramp Kit installation; nothing to prepare. Start Ramp Kit sessions on the installation branch.'
        exit 0
    fi
    echo 'This branch has no Ramp Kit installation. Start Ramp Kit sessions on the installation branch.' >&2
    exit 2
fi

if [ "$PHASE" = install ] || [ ! -x .ramp-venv/bin/python ]; then
    bash .ramp-kit/runtime/bootstrap.sh "$REPO"
fi
.ramp-venv/bin/python .ramp-kit/run.py --repo "$REPO" doctor
